---
abstract: 'assign an arrayref to an array sensibly'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  List::MoreUtils: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: List::AssignRef
name: List-AssignRef
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Sub::Exporter: 0
  lvalue: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=List-AssignRef
  homepage: https://metacpan.org/release/List-AssignRef
  license: http://dev.perl.org/licenses/
version: 0.002
